services:
  - type: web
    name: webstreaming
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
